#! /usr/bin/env python

import manageldap, argparse, getpass

# chfn [-f full_name] [-r room_no] [-w work_ph] [-h home_ph] [-o other] [user]
parser = argparse.ArgumentParser(description="Modify user information in the LDAP Directory.")
parser.add_argument('-f','--fullname',type=str,help='The new full name of the user.',default="")
parser.add_argument('-r','--roomno',type=str,help='The new room number of the user',default="")
parser.add_argument('-w','--phone',type=str,help='The new phone number of the user',default="")
parser.add_argument('-o','--other',type=str,help='The new value for the other field of the user',default='')
parser.add_argument("login",type=str,help='The username whose information is being modified.')
args = parser.parse_args()

moddeduser = manageldap.usermod(args.login,room=args.roomno,name=args.fullname,phone=args.phone,other=args.other)

manageldap.update(manageldap.getBindDn(),manageldap.server,moddeduser)
