#! /usr/bin/env python

from manageldap import *
import argparse

parser = argparse.ArgumentParser(description="Add users to LDAP Directory")
parser.add_argument('-a','--add',type=str,help='The user to add to the group.',default="")
parser.add_argument('-d','--delete',type=str,help='The user to delete from the group.',default="")
parser.add_argument('-g','--group',type=str,help='The name of the group.',required=True)
parser.add_argument('-l','--list',default=False,action='store_true',help='List the members of this group.')
parser.add_argument('-p','--purge',type=str,help='Remove all users from this group.',default="")
args = parser.parse_args()

moddedmems = groupmems(add=args.add,delete=args.delete,list=args.list,purge=args.purge,group=args.group)
update(moddedmems)
